apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prodesks-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: git@github.com:psyeo2/homelab-gitops.git
    targetRevision: main
    path: clusters/prodesks/apps
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
