apiVersion: v1
kind: ConfigMap
metadata:
  name: clankassist-pipeline-server
  namespace: apps
data:
  WHISPER_URL: http://192.168.1.161:8001
  PROCESS_URL: http://clankassist-process-api.apps.svc.cluster.local:3001
  PIPER_URL: http://clankassist-piper-api.apps.svc.cluster.local:5000
  LOG_LEVEL: SUMMARY
  PIPELINE_REQUEST_TIMEOUT_SECONDS: "120"
