apiVersion: apps/v1
kind: Deployment
metadata:
  name: clankassist-pipeline-server
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clankassist-pipeline-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clankassist-pipeline-server
    spec:
      containers:
        - name: pipeline-server
          image: 192.168.1.57/homelab/pipeline-server:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: clankassist-pipeline-server
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
