apiVersion: v1
kind: Service
metadata:
  name: clankassist-pipeline-server
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clankassist-pipeline-server
  ports:
    - name: http
      port: 8000
      targetPort: http
