- Bookmarks:
    - Gmail:
        - icon: gmail.png
          href: https://mail.google.com/
    - ChatGPT:
        - icon: chatgpt.png
          href: https://chatgpt.com/
    - Amazon:
        - icon: amazon.png
          href: https://www.amazon.co.uk/
    - eBay:
        - icon: ebay.png
          href: https://www.ebay.co.uk/
    - Reddit:
        - icon: reddit.png
          href: https://www.reddit.com/
    - YouTube:
        - icon: youtube.png
          href: https://www.youtube.com/
