title: Prodesks Homelab
description: Homelab service dashboard
target: _self
useEqualHeights: true
quicklaunch:
  provider: google
layout:
  Bookmarks:
    style: row
    columns: 5
  Media Services:
    style: row
    columns: 4
  Hardware Management:
    style: row
    columns: 3
  Home Automation:
    style: row
    columns: 3
  Game Servers:
    style: row
    columns: 3
  Networking:
    style: row
    columns: 3
  ARR Services:
    style: row
    columns: 3
