title: Prodesks Homelab
description: Homelab service dashboard
target: _self
useEqualHeights: true
fullWidth: true
quicklaunch:
  provider: google
layout:
  Hardware Management:
    style: row
    columns: 3
  Cluster:
    style: row
    columns: 3
  Bookmarks:
    style: row
    columns: 5
