- greeting:
    text_size: xl
    text: Hello, Eoin
- search:
    provider: google
    target: _blank
    focus: true
    showSearchSuggestions: true
- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hourCycle: h23
