---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared
  namespace: apps
spec:
  encryptedData:
    TUNNEL_TOKEN: AgAElQvxQqCxGq4Pf9gB5anzUJWexQcmTRQibCnQPcU5rvhlY3frbMVtpirMWxSrS6pwf1yesMGiu3zgVn6a7obi3acfOtDbe6sGlNcIh6JS1pRw3ih2EqhpRuSUXShjovApEf6SpgmpI/Ap/6YfSwd50uQG7wMhz7Q73+xImlfaKerO0XS4SUpxKL0iT+FwNm9zP0YYXfcUo0VTY5LHVSkl1E3MyCFe9siqRdjcyww3P5CB8HYW8TogriXJo5YG36bnQ6gIoWTX0jFWxk4p1sFgn0cvnduJVdjKojX+oQ6z76ySUedSXAps+ZNqqF80RHInUgOQ8nuHBdzKi31MjQXqgE5HJTqJVIIVvqSmj6bzVI/XTTjyr6DUO5HzXD3dCyeKCv4x5OJ55tupBuZlg8ANNnP+XUgse89ZmNaV7JPXeQjIiazwbYfVku7XZdZ/Bcv2dWS3ld4Skuo1K4UFD8gby+CymLL5Uv5QaisoJxAFHRaV9JXpxm/+JrpmGeKLSMqhCCEDjPEd6TTjbgZHS7ALxaKH/1TFyELNz3CDwkOu5/MTF/X7jZKGcBPngicSnUSdqEKM1U0KBZlQJa9jR6xWxFaXeXe2/G74Gqcfdn3YxmYdE3m74wD/dPzAztQKspsNQA3K2SxGpgeUoFoW2ZQ9UWIHE9z/J9yc8lOYFgSmkgdRErHWt/QixJPBbSeadnNIfZ0xm7AJy38WFWbRIf7CEQW9r37T339YbNPMNHStZbuBYDD0iJdObSrdNghV2wxQDSTgpzd8TuMrI6W2xQRCG6f0xx62FBVdkeYt5myNTut0l9nFYwqA2U6B3MZJ6mtp3lIZrLsY6HpDJw2NeZmwfhhCFeLEmTsEgZB981YidkBsPkCq2Jx+q50MgdeKM3u62TyYOFefv58hotP2saEhNsqrSUQSRxsAXAHnyPQ4XTAwsqEOMOSm
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared
      namespace: apps