apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: arr
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12000Gi
  storageClassName: jellyfin-media-nfs
  volumeName: jellyfin-media-nfs-pv-arr
