apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jellyfin-media-pv.yaml
  - jellyfin-media-pvc.yaml
  - arr-config-pvcs.yaml
  - qbittorrent-config-pvc.yaml
  - sealedsecret.yaml
  - qbittorrent-gluetun.yaml
  - arr-services.yaml
