---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arr
  namespace: arr
spec:
  encryptedData:
    WIREGUARD_MULLVAD_KEY: AgAMMffAlkuCPaIu4vZUzqoSz0JX5Srhfm3X2CMZ8BmNnlXHo3XxD2NF5FpyolqrAgPCKX/mcC5SkBeVXo/TkbbFI+iVA2x7AmjesPTDW+vfvNud+T+1FnNKYUm2OB+I5V58AJVx/e0iuRi1og2Ln4+4P+YUuqwGPBG6zIWfX0mmf7DKRtR4cx0sZ27Z/RMXzQlPrKhBDRMpLb4KLeJ5si3i5klXJgnQwr/kwMaEgGP4tIARlylN7jY5d77/BDBg5ZPeiBuOfRoIAimUV1MpbF5qMTVnGJHTQVyIhbXecQVo9zOVgSEqMkT4TIqRCSVMhwjrtPaQK8jGHwHXJP0zbseG7XN183AJRvIWBGsMK9xjNEbVMUV/msWZdSEaR4AHBzgXd5h9JoIeRyGxoH7MkEP8EkktB2wB+xEHQK2sRcx0gBqbSpjB4HhvOfSisCfZrEAjNC5ImBe86UsN9a6g71ICTKHq8dRpW5dzIa4/yJoio6oTlF/QREsan2hr7fkj4FBNgH1lnPYNhbudYvaGjVwsYJ1AAuMPbFekORh00C503iiTFbXeD5RGjHcuSJuncGawXz0SC/fjmFhz1Zh4/GcEd9K7h7isI0yUjEIgiX06INN3CtMywmjVOHm1NpF6okUrP6kTNkNHZsbOfMp/p31UQKAClJGmT4zqVfER+TCsr2rcfolB0q0mL+aMdeXst28HHfDboW/MgcBGoYDLnEhX2iSwbB+OwrN7R1FiaFeuBg5u93atZ7xvrdracQ==
  template:
    metadata:
      creationTimestamp: null
      name: arr
      namespace: arr
