---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arr
  namespace: apps
spec:
  encryptedData:
    WIREGUARD_MULLVAD_KEY: AgCHnbRag6wiQmBDf+q0FSfUk6xq11Tc9f2gK/aKJPc8kQZ/ORUrJLntRAd849r6YYEd3W0vSzT90K9UH2GimBjSb/vFeZBWV3AE2lqEypwjZFsidas/zA3DfdgextpVeNDjLbwo4W8rFWvDFQVpiB2IlYYuPIK8FoAUjkV+RenAjqEIq+UKAycQElg4iX1TvMMux42TBjOsObhxvfOtcXC9JBg1Es+2MZ+Zo0e5LeDVucNyQ/8GvPrhPa6Q/4+fcWmBh0I/7yL38kWbnSbwyfnHpNwUL89Q3qOGeU4IfK8Sw0v5+MZXmjHYoVTsqtml5fcE87QNSUKVNreYTG4IvmwfsrTGxCLNIou39EtLEP+9zwqUKInY4xFkMkdws/dE5Zl3Smevg+5ZdYccLtPbPyNNzxXGchc9SxrQ+mlDJdWWR7POIMr1WHraK8tedTNUg0+zfXaG8hXZ4BomBV7lIgD7bWbyGwbND2y41OYrBqL9PrHeWD3Cd3vebiJyq7q6LeWDYWgeS9vPNSY0RpyzY5h2emqwKL3Vu0LEvX+FFBc20p+y0ZU8VSvQ3Yrdj+iQZCme1gzD0VacY3Bk602kKWFIR3hlivCHMdy8hukkl39WKBQhoScxX75uwpcIuW4MdZvu4qYy3fJJAW6Wzs0XdCvaO2S5PVqGP38lSauTLHtclF9sO4A3gyE5emMvswSK4etQc1KwBxFiYqaq1acKBFBPahIpq9yC0eJS2QNCvoNQhfBAMXNmK2Hr+ZFEtg==
  template:
    metadata:
      creationTimestamp: null
      name: arr
      namespace: apps