---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: apps
spec:
  encryptedData:
    REDIS_PASSWORD: AgB1C5+K9lG9ZD3/y0m+N/THhjbW3pAZuesQNUfimjULYIYeQtHIUFtlWYRPEzz/V6rh9Sql8tyhL3Kqzeac83C7pqRseWXanacYtZRjDWPLuAH9ZDr+SesHWQUrRrHP/petv1+Y1wwBAiJiwzq0K7gko4ULSYLGiL5eseWm24JapJGAqLJu67Rf+53+fLKNhcSL6GRdFDGCMxTrkC/S+vbFbIQ8qT6THkbOJAA6qI+C4lKTfE8YDf8hzcQ+TpGNeOPfBaBuJWA+qt8pZGaMKqs3cpXKX1XRC/BE6Rka6H6kn24EW+bQgo9zKqRDs6dp3goS9WSJ3gl3SCifZyYAModlXRJswWkZz4Sm5DT32KBGdikThJHAAcFNI8EhrA/2kQ/i7uA9JLiFRsF1b43csFoPEBVmOGDzhBvijVx+wKQ418LEZQUFkv4NH6zLFELy7uy8TELJP86IR0k9KiwvlRDuN6ZYLOpQKlaJsozBin1kAOSZKN+6vRNcSoiwrso6gGNrlDp7t83d2uImnGbaRCrKKp5Sb9E6EI9scAPtjHaatExYzvI1UMaudsDBv+gcoEBcBBVVMOk+TX5QebSY6raDFSqGNBvep8EgaE35wCx5Y6D6LnevMHWrtrG0K9JE+kdzyaTlQpU0oTFSWKxZjWshQVDYZ+/Oj6xEVnWMVvawKzg6/1OGgamaU8hqDXOA0KdOYOLAM5cD5wtOn0s=
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: apps