---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  encryptedData:
    REDIS_DEFAULT_PASS: AgBsBvGbJswExX+D/p3hmvj0Np1wSF6uURHAn+lW7AtIYcIOvxiebqCR6pqbU3ItYHyIQG+CqUr7CdwQUmBw/OxngjgDoivIftLHIr5fwy951+80JKZRN5DORaHgiyHnqZgyuK3QEEhjnEiQzRypbsN+ilezxnqARoD54+fmS+2KnjGamPLaESCblHnJsrzMptaeFdzChgjzdAHR6osxYPxMzTFNkg8iI5G3gTgqYUZYyD5KQ0mtrEflgh23t9e/2UT3ivddMXOYuPlERhNMBYyOr5u2t5e+2la3oWxD+shk0kkqW5L6lR8W1yeP40HRl7DeRJHrmh60iv91zv8yKtK02M9NuxzgFGRy/FC46tnWGLPTS1/v2FP2k4vSxrDHawIWwv8Ayjnbi/94HNPgOfN5R/T7ETxGZuxljUyb16L1OhyqV5+OPhmdjIBR0fu1r/EFAvXS6VeHFWlEmyRQcY8doPeHLjiZRd85gtvonFoxmdWknZM9mPw3lLN4NxLFZMq6BBy8D9lDlNkvLPYpbGpQxDnFjhSIIWzo9nu3maWwwYdI4Q9k+boBWkdn1lSCgyWHd7V0lb+OJh0G8aLc6kit7gVLLbpnHPRqMGy6G6vHUjyUZlwwrM8kVNQ1ipQd6x7f+Jxg+gZk5Nkq664ZlzsItGCXHfRsTTkYLifu0ZswYoJC1n/bZm5fNpqwcHmnoWCx+Oi59Ai20hDE+ic6nhPKo3WImF1pJk2NGHC9gcd3864=
  template:
    metadata:
      creationTimestamp: null
      name: redis
      namespace: apps
