apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prodesks-postgres
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instances: 1
  bootstrap:
    initdb:
      database: app
      owner: app
  managed:
    services:
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: prodesks-postgres-rw-lb
            spec:
              type: LoadBalancer
              ports:
                - name: postgres
                  port: 5432
                  protocol: TCP
                  targetPort: 5432
  storage:
    storageClass: longhorn
    size: 20Gi
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
