apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prodesks-wireguard
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://helm-charts.rm3l.org
    chart: wg-easy
    targetRevision: 0.2.x
    helm:
      releaseName: wireguard
      values: |
        replicaCount: 1
        image:
          tag: "15"
        services:
          wg:
            type: LoadBalancer
            port: 51820
            loadBalancerIP: 192.168.1.51
            annotations:
              metallb.io/loadBalancerIPs: 192.168.1.51
          http:
            type: LoadBalancer
            port: 51821
            loadBalancerIP: 192.168.1.50
            annotations:
              metallb.io/loadBalancerIPs: 192.168.1.50
        persistence:
          enabled: true
          volumeClaimSpec:
            storageClassName: longhorn
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        extraEnvVars:
          env:
            - name: WG_HOST
              value: "192.168.1.51"
            - name: WG_PORT
              value: "51820"
            - name: INSECURE
              value: "true"
  destination:
    name: in-cluster
    namespace: wireguard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
