apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prodesks-longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.10.x
    helm:
      releaseName: longhorn
      values: |
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
        csi:
          kubeletRootDir: /var/lib/kubelet
        defaultSettings:
          kubeletRootDir: /var/lib/kubelet
          defaultDataPath: /var/lib/longhorn
  destination:
    name: in-cluster
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
