apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: kubelet-root-dir
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "40"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
value: /var/lib/kubelet
