apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: apps
  annotations:
    argocd.argoproj.io/sync-wave: "16"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 12000Gi
  storageClassName: immich-nfs
  volumeName: immich-library-nfs-pv
