apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-external-media-nfs-pv
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  capacity:
    storage: 12000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-external-media-nfs
  mountOptions:
    - nfsvers=3
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: 192.168.1.165
    path: /var/nfs/shared/Photos
