---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: immich-psql-password
  namespace: apps
spec:
  encryptedData:
    IMMICH_PW: AgAEe+147X29+9g43jGrvQ5l2vEpvGVDPAqaBrLR6zSaSuW11MD3N0Pe+/X6SmYu2K+OVbn9qWeh4x7XobrKsNyc0yTEo8jdwRdjtPaTS4zIckzHfu4oHI3SIDEDoUjOxm89bDSD2nujk17ucGQwxHp+W1pR76l+nZCbB+lcLGuAVyu7jGC4OdbvxnPwILhLeohua1ZPbcWK9/Hby+z89Y0+3N9/6Xfn/HTCfuu8ITAch4EqqvujXrTw6czb/ZNZ/OJ9z8VPu2xg0a2KrN58I3USgydDGHysM0hN/7bUvWXAt0QoY5JqF9GN3GKJ8eyXvzRI+owKeUlImUGPgVIM1QxsBmlPuZpNrTh+/FZKsUa5VyojQaVv8/y/t+3uGi/90u2L3kJpeRjokvwh1nNCGIl+ZT7KodQb8W4uoRVoy12veCTdXiMQeuN6W4MGmWKMVVrYpjVGyMehy9CIspKRtGTy7VbwrQA/hFfw+vCtRNDfNaUpnYE/5dpVGiK/H7GpvHhlgCSeMWUClErVWIHuexM77197lqGdzxE2+GIQHKMnUq3WX1ZC8K2jodW0IskIvwSXNndye0Iz/g/E5F/38B+H7BqTYm4zvmG851psLFPV0KUsAkf4hvGy2pljx0aMyS0Ly9zm+66DZYpxz2lRu0xKHt1S1LZtBSwSoq9nTL90yCyvJ1RSnwFq3MhfM794lg/KIEXTe/9Tyodlo36G+Ak8CnYfY28B2vIbq7qL39ptag==
  template:
    metadata:
      creationTimestamp: null
      name: immich-psql-password
      namespace: apps