apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prodesks-prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.10.3
    helm:
      releaseName: monitoring
      values: |
        fullnameOverride: monitoring

        alertmanager:
          enabled: false

        kubeEtcd:
          enabled: false

        kubeControllerManager:
          enabled: false

        kubeScheduler:
          enabled: false

        kubeProxy:
          enabled: false

        kubelet:
          jobNameOverride: k3s-server

        grafana:
          enabled: false

        prometheus:
          prometheusSpec:
            retention: 15d
            scrapeInterval: 30s
            evaluationInterval: 30s
            additionalScrapeConfigs:
              - job_name: external-node-exporter
                static_configs:
                  - targets:
                      - 192.168.1.20:9100
                      - 192.168.1.161:9100
                      - 192.168.1.165:9100
                    labels:
                      site: prodesks-homelab
              - job_name: external-dcgm-exporter
                static_configs:
                  - targets:
                      - 192.168.1.161:9400
                    labels:
                      host: ubuntu-gpu-vm
                      site: prodesks-homelab
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 40Gi

        prometheus-node-exporter:
          extraArgs:
            - --collector.systemd
            - --collector.processes
          service:
            labels:
              job: node
          prometheus:
            monitor:
              jobLabel: job
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ClientSideApplyMigration=false
