apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: oznu/cloudflare-ddns:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: API_KEY
            - name: ZONE
              value: 7marketplace.uk
            - name: SUBDOMAIN
              value: ddns
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
