---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-ddns
  namespace: apps
spec:
  encryptedData:
    API_KEY: AgB508ZUEHgunh8VK8lsAGNZdNKpFujQ2fDHto5LiOtTSjUVXDZqf+KTQwU/jhd1nq6Eo7bk01NrAWfMxMe5KmDAhjl0QWvkq7+266h8S0564tDdgUAmg0HGdWx2S/haI2Ut8vjKYOmbKOJuURMt6Hd3eke8y4PDPNV0cLeCo+xd62WBm5ywp1Di1FtD2lPpqojSsXn2cxw2aDG32hbbP7XLFsoxMsGNNQMYGXR2Q3nEOttpwfTdordNarevphndK7+UODk0CuMHJGSCvdJwIb5rkOYQJhJPv25iwzqlt0899VuVzCRc8IR52rmFOWb3u+pcA1pIlhNAFQRJcKIiRAWlLx4aj8l6xQHe18PpTb0I1Q6zxo5MCKDIHGT6HZM2IRzVc1/3qRlu+yxBcb0pApvB0l29HA+LhOkcxaLFJ48EGMHUdQEzwpfMmaVIJi9daUAZ0nI0nZuZgKOcLJQ+tKXQ1d3ETbNLHQEgZPwF9+W5ROjfPkJKR5s/XVn7wc0FNwoJ9X0hUgliUnhLcZvyeRFiL/GqhU2OCDQGveglcUupSRgFPoJZKrZ8QiOH7EHz/H12S48NLUUVz7sWSbmP8WcZMjJNfFeGU8YXvNOeZTrJovpduBU6PKEKDkMrXVRNDfniysWfxSGh2SzIXIxBtMlj9LyD2zAaOU/Sd/wzV/kj9RJDItvIawHbhkKTbTAuk5buvcW+DJEC6plPT0KFYHIFp4XFBfV9p/uBWZRWZKzaZpLVC/HIwV00
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-ddns
      namespace: apps