apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prodesks-grafana-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "29"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 82.10.1
    helm:
      releaseName: grafana-crds
      values: |
        crds:
          enabled: true
        defaultRules:
          create: false
        grafana:
          enabled: false
        prometheus:
          enabled: false
        alertmanager:
          enabled: false
        kube-state-metrics:
          enabled: false
        prometheus-node-exporter:
          enabled: false
        prometheusOperator:
          enabled: false
  destination:
    name: in-cluster
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
