apiVersion: v1
kind: ConfigMap
metadata:
  name: clankassist-process-api
  namespace: apps
data:
  API_VERSION: "1"
  PORT: "3001"
  LOG_LEVEL: SUMMARY
  OLLAMA_URL: http://192.168.1.161:11434
  OLLAMA_MODEL: gemma3:4b
  GPU_EXPORTER_URL: http://192.168.1.161:9400
  GPU_TEMPERATURE_METRIC: DCGM_FI_DEV_GPU_TEMP
  GPU_VRAM_USED_METRIC: DCGM_FI_DEV_FB_USED
  GPU_VRAM_FREE_METRIC: DCGM_FI_DEV_FB_FREE
  GPU_VOLATILE_UTILISATION_METRIC: DCGM_FI_DEV_GPU_UTIL
  JELLYSEERR_API_URL: http://192.168.1.56:5055
  JELLYSEERR_API_KEY: ""
  JELLYSEERR_REQUEST_USER_ID: ""
