apiVersion: v1
kind: Service
metadata:
  name: clankassist-process-api
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clankassist-process-api
  ports:
    - name: http
      port: 3001
      targetPort: http
