apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prodesks-harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.18.1
    helm:
      releaseName: harbor
      values: |
        expose:
          type: loadBalancer
          tls:
            enabled: false
            certSource: none
          loadBalancer:
            name: harbor
            IP: 192.168.1.57
            ports:
              httpPort: 80
              httpsPort: 443

        externalURL: http://192.168.1.57

        persistence:
          enabled: true
          resourcePolicy: keep
          persistentVolumeClaim:
            registry:
              storageClass: longhorn
              accessMode: ReadWriteOnce
              size: 50Gi
            jobservice:
              jobLog:
                storageClass: longhorn
                accessMode: ReadWriteOnce
                size: 2Gi
            database:
              storageClass: longhorn
              accessMode: ReadWriteOnce
              size: 5Gi
            redis:
              storageClass: longhorn
              accessMode: ReadWriteOnce
              size: 2Gi

        existingSecretAdminPassword: harbor
        existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
        existingSecretSecretKey: harbor

        trivy:
          enabled: false

        metrics:
          enabled: true
          serviceMonitor:
            enabled: true

        portal:
          replicas: 1

        core:
          replicas: 1

        jobservice:
          replicas: 1

        registry:
          replicas: 1

        chartmuseum:
          enabled: false

        notary:
          enabled: false
  destination:
    name: in-cluster
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
