---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor
  namespace: apps
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgAAEhaZUxAGdTlcJexAXl807RPTlum3gA4exvdDh6d35GjeZ4HXNj130b8JV1XHevt/pDfv/4IxD4lgkksW2TZhqCdzJco+t0JRryDhUH2IfS1pZTn8AoZx7cvbRDOeREkLX904bEEHC6pAQGmft/BSOUuxCBrU6RMtPorVc98hhuUofJerLSbw2uoyscomY9DwfCWUU0FfzuTarkNfxEPVIaunG+enh9l3srIRJQLr/RfGmfUQqWo8gSSwC6EqZHdYe9FvZHQ17sezsANmXjXCHQnNzTSz7I3IXKOiU155BB50B/QFdqN17X4YDKae+igtfRSDKILtdie+hBmzoiFKH6EZMFvdD81bPUca0VRF2jfr4vTFF98+BZP+sY68k4kevXW6wAzU3RQWafzrkbv7Wd2LFirT5lA3jP0OpeBN6O5lub4q6sj+9A4sFORnZzC/CICKekrZ3CLP15T20GwdlFNh7ICE6llfWDsMklzn0LPI6SQDvletFcgz0/0OIiFLhatz8mPibi9kj0cVPXJxyu1X+qQsz7Y4+BnxQ1TCt9fl0QasnyyjjR1uhsZOR9r6GWHjV7PZ4yuBzA0ok2nXqw/gokwvfSu9kfP2+PvZhQ6VEMEYWvi1tp8S+bw/gvvrn/7bp6oz7/rkzib0vwBEKEuVe4hIjAVPbQBGd5uywIR6WGl/5dYDOyWXneMhWxq3OtR5JMhMsmWmFDI=
    secretKey: AgBwIPEgh4SPzy0bakrs96lRDju1NSmK3FLjititJpFR4g1e9QXXL8XorckqBfINHcBTXj/DP+wo21KQfK8S/tZlTPDjSSPIpZ1VN9oglynpsdI6QctnESpLYk4gy1HZkrgrCyxKbmx/iQkVdWQSMPMxARPy+SfuwzTtk8pQDf+2WsbFRAA5G/CCx2cW2u9oAlw6aVaJh2iA2OxBdbpl7tk9wa9rvP1ftfm12nIemiS3G0q/BKc0lhid7SN4+BY9AD6c3sJFireNvJTgUdP0VIsdv5lhCLlWZ7ibSW46Gf+tTtUvDp6SdsuoOZ9ynRVyjlFenXzUWlE/L2kHytCfm5UAzPrZRsQwwMUD5DXU7fJ/PJ4jRNPEPFzKdZzyWN0Vt1FrOO60PHjYuGd8AmQ43UqB/mvvjHWdM0faWNNXYBxk2kWDSUzSeC/pF4PCwD7MKgnsMiWWLUK6TBA/nyl65OvutGziTEvGlLTBwAYSwOFSEiPC7gv++aDXlgWHmStBwYfawNapOwmu3kNo8SXBEIc6TS/RVGkD+Y35/AM54zlCoiQVS6k0FWcKZIFgDZAlAaiQzu4BvLyYi2mHjaVWafpQ79Ecaj40gPVCbx2eNWcN9sQg+NyKql21T4kTOOq6fo2PbnFnFq4qEkO5qiE9CrgVBOYEa02p0mhF0KDBT7tGT7LminDpkVoqXFYdbed7o7rOETgyqOP5hsNMFlRkq9PfPQG7ZGtjbnb5n6Di2JXsxQ==
  template:
    metadata:
      creationTimestamp: null
      name: harbor
      namespace: apps
